In [ ]:
TASK - 2: MALL E-COMMERCE MESSY DATASET:

In [ ]:
Division 1 — Load and inspect
What: Load the CSV and inspect its dimensions, sample rows, columns, and data types.
Why: Understand the structure before changing anything.
Outcome: A baseline view of the original data and its quality issues.

In [1]:
import pandas as pd
import numpy as np

# Keep the CSV in the same folder as this notebook.
df_original = pd.read_csv("mall_ecommerce_messy_dataset.csv")
df = df_original.copy()

print("Rows and columns:", df.shape)
display(df.head(10))
df.info()
display(df.describe(include="all").T)

Rows and columns: (123, 12)

,Order_ID,Order_Date,Mall,City,Product,Category,Quantity,Unit_Price_INR,Discount,Sales_Channel,Customer_Age,Customer_Rating
0,ORD-0001,2025-05-10,Mall Central,Chennai,Coffee Mug,Home & Living,1.0,244.43,0.15,Click & Collect,62.0,4.2
1,ORD-0002,2025-08-09,mall central,Bengaluru,Water Bottle,Home & Living,2.0,455.93,0.00,In-Store,57.0,4.5
2,ORD-0003,15/03/2025,Mall Central,Mumbai,Keyboard,Electronics,4.0,1772.22,0.00,In-Store,37.0,4.8
3,ORD-0004,2025-06-13,Riverside Mall,Chennai,Power Bank,Electronics,6.0,1424.78,0.15,In-Store,41.0,3.1
4,ORD-0005,NaN,City Square,Bengaluru,USB-C Cable,Electronics,1.0,259.87,0.10,Click & Collect,61.0,4.1
5,ORD-0006,2025-01-21,Mall Central,Mumbai,Power Bank,Electronics,2.0,1242.31,0.15,In-Store,68.0,4.7
6,ORD-0007,2025-04-20,Grand Arcade,Pune,Keyboard,Electronics,-3.0,1634.20,0.15,In-Store,42.0,2.6
7,ORD-0008,2025-10-04,NaN,Hyderabad,Desk Lamp,Home & Living,4.0,1264.84,0.00,In-Store,56.0,4.9
8,ORD-0009,2025-01-23,CITY SQUARE,Pune,T-Shirt,Fashion,3.0,671.84,0.05,Online,42.0,3.0
9,ORD-0010,2025-04-10,City Square,Bengaluru,Water Bottle,Home & Living,4.0,396.09,0.00,Online,29.0,4.2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         123 non-null    object
 1   Order_Date       120 non-null    object
 2   Mall             120 non-null    object
 3   City             121 non-null    object
 4   Product          121 non-null    object
 5   Category         123 non-null    object
 6   Quantity         121 non-null    float64
 7   Unit_Price_INR   121 non-null    float64
 8   Discount         121 non-null    float64
 9   Sales_Channel    121 non-null    object
 10  Customer_Age     120 non-null    float64
 11  Customer_Rating  120 non-null    float64
dtypes: float64(5), object(7)
memory usage: 11.7+ KB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Order_ID,123,120,ORD-0031,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order_Date,120,101,2025-01-02,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mall,120,10,Grand Arcade,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,121,8,Chennai,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product,121,17,Keyboard,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,123,6,Electronics,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,121.0,NaN,NaN,NaN,14.157025,93.03288,-3.0,2.0,4.0,6.0,999.0
Unit_Price_INR,121.0,NaN,NaN,NaN,1973.866364,9023.645532,-250.0,455.93,1084.43,1717.84,99999.0
Discount,121.0,NaN,NaN,NaN,0.108264,0.166752,0.0,0.0,0.1,0.15,1.75
Sales_Channel,121,5,In-Store,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_Age,120.0,NaN,NaN,NaN,42.916667,19.005343,4.0,28.75,41.0,56.25,150.0
Customer_Rating,120.0,NaN,NaN,NaN,3.709167,0.939157,-1.0,3.075,3.7,4.3,8.5

In [ ]:
Division 2 — Identify and handle missing values
What: Use isnull(), isna(), sum(), dropna(), and fillna() to investigate missing data.
Why: Missing data can break calculations or bias summaries; dropping every incomplete row can discard useful records.
Outcome: A missing-value report and an informed strategy for handling gaps.

In [2]:

display(df.isnull().head())
display(df.isna().head())

missing_counts = df.isna().sum().sort_values(ascending=False)
display(missing_counts[missing_counts > 0].to_frame("Missing_Count"))

print("Original shape:", df.shape)
dropna_demo = df.dropna()
print("Shape after dropping rows with any missing value:", dropna_demo.shape)

# We will not drop every incomplete row from the working dataset automatically.

,Order_ID,Order_Date,Mall,City,Product,Category,Quantity,Unit_Price_INR,Discount,Sales_Channel,Customer_Age,Customer_Rating
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,True,False,False,False,False,False,False,False,False,False,False

,Order_ID,Order_Date,Mall,City,Product,Category,Quantity,Unit_Price_INR,Discount,Sales_Channel,Customer_Age,Customer_Rating
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,True,False,False,False,False,False,False,False,False,False,False

                 Missing_Count
Order_Date                   3
Mall                         3
Customer_Age                 3
Customer_Rating              3
City                         2
Product                      2
Quantity                     2
Unit_Price_INR               2
Discount                     2
Sales_Channel                2

Original shape: (123, 12)
Shape after dropping rows with any missing value: (99, 12)

In [ ]:
Division 3 — Basic statistical analysis:
What: Calculate sums, means, medians, and descriptive statistics before cleaning.
Why: Invalid values and outliers can distort business metrics.
Outcome: Baseline statistics to compare with the cleaned dataset.

In [3]:
numeric_cols = ["Quantity", "Unit_Price_INR", "Discount", "Customer_Age", "Customer_Rating"]

print("BEFORE CLEANING")
display(df_original[numeric_cols].agg(["sum", "mean", "median"]).T)
display(df_original[numeric_cols].describe().T)

BEFORE CLEANING

                       sum         mean   median
Quantity           1713.00    14.157025     4.00
Unit_Price_INR   238837.83  1973.866364  1084.43
Discount             13.10     0.108264     0.10
Customer_Age       5150.00    42.916667    41.00
Customer_Rating     445.10     3.709167     3.70

,count,mean,std,min,25%,50%,75%,max
Quantity,121.0,14.157025,93.032880,-3.0,2.000,4.00,6.00,999.00
Unit_Price_INR,121.0,1973.866364,9023.645532,-250.0,455.930,1084.43,1717.84,99999.00
Discount,121.0,0.108264,0.166752,0.0,0.000,0.10,0.15,1.75
Customer_Age,120.0,42.916667,19.005343,4.0,28.750,41.00,56.25,150.00
Customer_Rating,120.0,3.709167,0.939157,-1.0,3.075,3.70,4.30,8.50

In [ ]:
Division 4 — Standardize text and dates
What: Trim spaces, standardize capitalization and known variants, and parse dates.
Why: "chennai", " CHENNAI ", and "Bangalore" should not accidentally be counted as separate categories.
Outcome: Consistent labels and a datetime column; invalid dates become NaT for review.

In [4]:
text_cols = ["Mall", "City", "Product", "Category", "Sales_Channel"]

for col in text_cols:
    df[col] = df[col].astype("string").str.strip().str.title()

# Correct known variants using explicit mapping rules.
df["City"] = df["City"].replace({"Bangalore": "Bengaluru", "Hydrabad": "Hyderabad"})
df["Product"] = df["Product"].replace({"Usb C Cable": "USB-C Cable"})
df["Sales_Channel"] = df["Sales_Channel"].replace({"Click And Collect": "Click & Collect"})

# Parse mixed date formats; invalid/impossible dates become NaT.
df["Order_Date"] = pd.to_datetime(df["Order_Date"], format="mixed", errors="coerce")

display(df[["Mall", "City", "Product", "Category", "Sales_Channel", "Order_Date"]].head(15))
print("Missing/unparseable dates:", df["Order_Date"].isna().sum())

,Mall,City,Product,Category,Sales_Channel,Order_Date
0,Mall Central,Chennai,Coffee Mug,Home & Living,Click & Collect,2025-05-10
1,Mall Central,Bengaluru,Water Bottle,Home & Living,In-Store,2025-08-09
2,Mall Central,Mumbai,Keyboard,Electronics,In-Store,2025-03-15
3,Riverside Mall,Chennai,Power Bank,Electronics,In-Store,2025-06-13
4,City Square,Bengaluru,Usb-C Cable,Electronics,Click & Collect,NaT
5,Mall Central,Mumbai,Power Bank,Electronics,In-Store,2025-01-21
6,Grand Arcade,Pune,Keyboard,Electronics,In-Store,2025-04-20
7,<NA>,Hyderabad,Desk Lamp,Home & Living,In-Store,2025-10-04
8,City Square,Pune,T-Shirt,Fashion,Online,2025-01-23
9,City Square,Bengaluru,Water Bottle,Home & Living,Online,2025-04-10
10,Mall Central,Pune,Usb-C Cable,Electronics,In-Store,2025-04-07
11,Metro Plaza,Mumbai,Backpack,Accessories,Online,2025-09-10
12,Mall Central,<NA>,T-Shirt,Fashion,Click & Collect,2025-09-07
13,Riverside Mall,Chennai,Usb-C Cable,Electronics,Click & Collect,2025-05-22
14,Grand Arcade,Hyderabad,Water Bottle,Home & Living,Click & Collect,2025-01-12

Missing/unparseable dates: 6

In [ ]:
Division 5 — Convert data types and validate numeric ranges
What: Convert numeric columns with pd.to_numeric(), inspect dtypes/info(), and flag impossible values.
Why: Numeric-looking text cannot be safely calculated, and values such as negative quantities or discounts above 100% violate this exercise's business rules.
Outcome: Consistent numeric types and invalid values isolated for review.

In [5]:
print("Data types before conversion:")
display(df.dtypes.to_frame("dtype"))
df.info()

numeric_cols = ["Quantity", "Unit_Price_INR", "Discount", "Customer_Age", "Customer_Rating"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# These are example business rules; confirm rules with a data owner in real work.
df.loc[df["Quantity"] <= 0, "Quantity"] = np.nan
df.loc[df["Unit_Price_INR"] <= 0, "Unit_Price_INR"] = np.nan
df.loc[~df["Discount"].between(0, 1), "Discount"] = np.nan
df.loc[~df["Customer_Age"].between(18, 100), "Customer_Age"] = np.nan
df.loc[~df["Customer_Rating"].between(1, 5), "Customer_Rating"] = np.nan

print("Data types after conversion and validation:")
display(df.dtypes.to_frame("dtype"))
display(df[numeric_cols].describe().T)

Data types before conversion:

                          dtype
Order_ID                 object
Order_Date       datetime64[ns]
Mall             string[python]
City             string[python]
Product          string[python]
Category         string[python]
Quantity                float64
Unit_Price_INR          float64
Discount                float64
Sales_Channel    string[python]
Customer_Age            float64
Customer_Rating         float64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         123 non-null    object
 1   Order_Date       117 non-null    datetime64[ns]
 2   Mall             120 non-null    string
 3   City             121 non-null    string
 4   Product          121 non-null    string
 5   Category         123 non-null    string
 6   Quantity         121 non-null    float64
 7   Unit_Price_INR   121 non-null    float64
 8   Discount         121 non-null    float64
 9   Sales_Channel    121 non-null    string
 10  Customer_Age     120 non-null    float64
 11  Customer_Rating  120 non-null    float64
dtypes: datetime64[ns](1), float64(5), object(1), string(5)
memory usage: 11.7+ KB
Data types after conversion and validation:

                          dtype
Order_ID                 object
Order_Date       datetime64[ns]
Mall             string[python]
City             string[python]
Product          string[python]
Category         string[python]
Quantity                float64
Unit_Price_INR          float64
Discount                float64
Sales_Channel    string[python]
Customer_Age            float64
Customer_Rating         float64

,count,mean,std,min,25%,50%,75%,max
Quantity,119.0,14.420168,93.795260,1.00,2.00,4.00,6.000,999.0
Unit_Price_INR,119.0,2009.141429,9095.608754,0.01,472.78,1087.45,1722.670,99999.0
Discount,120.0,0.094583,0.072121,0.00,0.00,0.10,0.150,0.2
Customer_Age,118.0,42.338983,16.002788,18.00,29.00,41.00,56.000,99.0
Customer_Rating,118.0,3.708475,0.715109,2.50,3.10,3.70,4.275,4.9

In [ ]:
Division 6 — Detect duplicates
What: Count exact duplicate rows and inspect repeated order IDs.
Why: Duplicates can inflate sales, but repeated IDs with conflicting data may require investigation.
Outcome: Exact duplicates are removed; repeated identifiers are flagged rather than blindly discarded.

In [6]:
print("Exact duplicate rows:", df.duplicated().sum())

duplicate_ids = df[df["Order_ID"].duplicated(keep=False)].sort_values("Order_ID")
display(duplicate_ids)

df = df.drop_duplicates().copy()
print("Shape after removing exact duplicate rows:", df.shape)

repeated_id_mask = df["Order_ID"].duplicated(keep=False)
print("Rows with repeated Order_IDs needing review:", repeated_id_mask.sum())
display(df.loc[repeated_id_mask].sort_values("Order_ID"))

Exact duplicate rows: 2

,Order_ID,Order_Date,Mall,City,Product,Category,Quantity,Unit_Price_INR,Discount,Sales_Channel,Customer_Age,Customer_Rating
11,ORD-0012,2025-09-10,Metro Plaza,Mumbai,Backpack,Accessories,6.0,1636.05,0.20,Online,38.0,3.2
120,ORD-0012,2025-09-10,Metro Plaza,Mumbai,Backpack,Accessories,6.0,1636.05,0.20,Online,38.0,3.2
20,ORD-0021,2025-05-06,Mall Central,Mumbai,Sunglasses,Fashion,7.0,970.94,0.15,Click & Collect,60.0,2.9
121,ORD-0021,2025-05-06,Mall Central,Mumbai,Sunglasses,Fashion,7.0,970.94,0.15,Click & Collect,60.0,2.9
30,ORD-0031,2025-07-08,Grand Arcade,Pune,Water Bottle,Home & Living,1.0,416.94,0.10,Click & Collect,22.0,3.5
122,ORD-0031,2025-07-08,Grand Arcade,Pune,Water Bottle,Home & Living,5.0,416.94,0.10,Click & Collect,22.0,3.5

Shape after removing exact duplicate rows: (121, 12)
Rows with repeated Order_IDs needing review: 2

,Order_ID,Order_Date,Mall,City,Product,Category,Quantity,Unit_Price_INR,Discount,Sales_Channel,Customer_Age,Customer_Rating
30,ORD-0031,2025-07-08,Grand Arcade,Pune,Water Bottle,Home & Living,1.0,416.94,0.1,Click & Collect,22.0,3.5
122,ORD-0031,2025-07-08,Grand Arcade,Pune,Water Bottle,Home & Living,5.0,416.94,0.1,Click & Collect,22.0,3.5

In [ ]:
Division 7 — Detect and handle outliers
What: Use describe() and the IQR method to flag potential outliers in quantity and unit price.
Why: Extreme values can distort averages and revenue, but an unusual value is not automatically wrong.
Outcome: Potential outliers are displayed for investigation and an explicit handling decision.

In [7]:
outlier_cols = ["Quantity", "Unit_Price_INR"]
display(df[outlier_cols].describe().T)

def iqr_outlier_report(data, column):
    q1 = data[column].quantile(0.25)
    q3 = data[column].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    mask = (data[column] < lower) | (data[column] > upper)
    print(f"{column}: Q1={q1:.2f}, Q3={q3:.2f}, IQR={iqr:.2f}")
    print(f"Lower bound={lower:.2f}, upper bound={upper:.2f}, outliers={mask.sum()}")
    return data.loc[mask, ["Order_ID", "Product", column]]

for col in outlier_cols:
    display(iqr_outlier_report(df, col))

,count,mean,std,min,25%,50%,75%,max
Quantity,117.0,14.555556,94.594547,1.00,2.00,4.00,6.0,999.0
Unit_Price_INR,117.0,2021.203761,9173.104217,0.01,458.74,1087.45,1727.5,99999.0

Quantity: Q1=2.00, Q3=6.00, IQR=4.00
Lower bound=-4.00, upper bound=12.00, outliers=2

    Order_ID     Product  Quantity
55  ORD-0056    Notebook     999.0
93  ORD-0094  Power Bank     250.0

Unit_Price_INR: Q1=458.74, Q3=1727.50, IQR=1268.76
Lower bound=-1444.40, upper bound=3630.64, outliers=1

    Order_ID     Product  Unit_Price_INR
60  ORD-0061  Headphones         99999.0

In [ ]:
Handling decision: Investigate flagged records first. For this synthetic dataset, ₹99,999 is a suspicious unit price; mark it missing pending verification. Keep other flagged observations unless there is evidence they are errors.

In [8]:
# Demonstration only: correct a known suspicious synthetic value pending verification.
df.loc[df["Unit_Price_INR"] == 99999.00, "Unit_Price_INR"] = np.nan

# Optional capping demonstration: create a separate capped quantity column; don't overwrite Quantity.
q1 = df["Quantity"].quantile(0.25)
q3 = df["Quantity"].quantile(0.75)
iqr = q3 - q1
lower_bound = max(1, q1 - 1.5 * iqr)
upper_bound = q3 + 1.5 * iqr
df["Quantity_Capped_Demo"] = df["Quantity"].clip(lower=lower_bound, upper=upper_bound)
display(df[["Order_ID", "Quantity", "Quantity_Capped_Demo"]].head(10))

   Order_ID  Quantity  Quantity_Capped_Demo
0  ORD-0001       1.0                   1.0
1  ORD-0002       2.0                   2.0
2  ORD-0003       4.0                   4.0
3  ORD-0004       6.0                   6.0
4  ORD-0005       1.0                   1.0
5  ORD-0006       2.0                   2.0
6  ORD-0007       NaN                   NaN
7  ORD-0008       4.0                   4.0
8  ORD-0009       3.0                   3.0
9  ORD-0010       4.0                   4.0

In [ ]:
Division 8 — Handle missing values and create Revenue
What: Impute remaining numeric gaps with medians and categorical gaps with modes, then calculate net revenue.
Why: This produces a usable analysis dataset while avoiding revenue calculations on invalid inputs.
Outcome: A cleaned working dataset with a Revenue column.

In [9]:
numeric_fill_cols = ["Quantity", "Unit_Price_INR", "Discount", "Customer_Age", "Customer_Rating"]
for col in numeric_fill_cols:
    df[col] = df[col].fillna(df[col].median())

categorical_fill_cols = ["Mall", "City", "Product", "Category", "Sales_Channel"]
for col in categorical_fill_cols:
    modes = df[col].mode(dropna=True)
    if not modes.empty:
        df[col] = df[col].fillna(modes.iloc[0])

# Keep missing dates for review rather than inventing dates.
df["Revenue"] = (df["Quantity"] * df["Unit_Price_INR"] * (1 - df["Discount"])).round(2)

display(df.head(10))
display(df.isna().sum().to_frame("Remaining_Missing_Count"))
print("Revenue formula: Quantity × Unit_Price_INR × (1 − Discount)")

,Order_ID,Order_Date,Mall,City,Product,Category,Quantity,Unit_Price_INR,Discount,Sales_Channel,Customer_Age,Customer_Rating,Quantity_Capped_Demo,Revenue
0,ORD-0001,2025-05-10,Mall Central,Chennai,Coffee Mug,Home & Living,1.0,244.43,0.15,Click & Collect,62.0,4.2,1.0,207.77
1,ORD-0002,2025-08-09,Mall Central,Bengaluru,Water Bottle,Home & Living,2.0,455.93,0.00,In-Store,57.0,4.5,2.0,911.86
2,ORD-0003,2025-03-15,Mall Central,Mumbai,Keyboard,Electronics,4.0,1772.22,0.00,In-Store,37.0,4.8,4.0,7088.88
3,ORD-0004,2025-06-13,Riverside Mall,Chennai,Power Bank,Electronics,6.0,1424.78,0.15,In-Store,41.0,3.1,6.0,7266.38
4,ORD-0005,NaT,City Square,Bengaluru,Usb-C Cable,Electronics,1.0,259.87,0.10,Click & Collect,61.0,4.1,1.0,233.88
5,ORD-0006,2025-01-21,Mall Central,Mumbai,Power Bank,Electronics,2.0,1242.31,0.15,In-Store,68.0,4.7,2.0,2111.93
6,ORD-0007,2025-04-20,Grand Arcade,Pune,Keyboard,Electronics,4.0,1634.20,0.15,In-Store,42.0,2.6,NaN,5556.28
7,ORD-0008,2025-10-04,Grand Arcade,Hyderabad,Desk Lamp,Home & Living,4.0,1264.84,0.00,In-Store,56.0,4.9,4.0,5059.36
8,ORD-0009,2025-01-23,City Square,Pune,T-Shirt,Fashion,3.0,671.84,0.05,Online,42.0,3.0,3.0,1914.74
9,ORD-0010,2025-04-10,City Square,Bengaluru,Water Bottle,Home & Living,4.0,396.09,0.00,Online,29.0,4.2,4.0,1584.36

                      Remaining_Missing_Count
Order_ID                                    0
Order_Date                                  6
Mall                                        0
City                                        0
Product                                     0
Category                                    0
Quantity                                    0
Unit_Price_INR                              0
Discount                                    0
Sales_Channel                               0
Customer_Age                                0
Customer_Rating                             0
Quantity_Capped_Demo                        4
Revenue                                     0

Revenue formula: Quantity × Unit_Price_INR × (1 − Discount)

In [ ]:
Division 9 — Compare before and after cleaning
What: Compare row counts, missing values, data types, and statistical measures.
Why: We need to measure how the cleaning process changed the dataset.
Outcome: A transparent summary of the impact of cleaning.

In [10]:
print("Original shape:", df_original.shape)
print("Cleaned shape:", df.shape)

comparison_missing = pd.DataFrame({
    "Before": df_original.isna().sum(),
    "After": df.isna().sum()
}).fillna(0).astype(int)
display(comparison_missing)

print("Original data types:")
display(df_original.dtypes.to_frame("Original dtype"))
print("Cleaned data types:")
display(df.dtypes.to_frame("Cleaned dtype"))

comparison_stats = pd.DataFrame({
    "Before_Mean": df_original[numeric_cols].mean(numeric_only=True),
    "After_Mean": df[numeric_cols].mean(numeric_only=True),
    "Before_Median": df_original[numeric_cols].median(numeric_only=True),
    "After_Median": df[numeric_cols].median(numeric_only=True),
})
display(comparison_stats)
print("Total revenue in cleaned dataset:", round(df["Revenue"].sum(), 2))

Original shape: (123, 12)
Cleaned shape: (121, 14)

                      Before  After
Category                   0      0
City                       2      0
Customer_Age               3      0
Customer_Rating            3      0
Discount                   2      0
Mall                       3      0
Order_Date                 3      6
Order_ID                   0      0
Product                    2      0
Quantity                   2      0
Quantity_Capped_Demo       0      4
Revenue                    0      0
Sales_Channel              2      0
Unit_Price_INR             2      0

Original data types:

                Original dtype
Order_ID                object
Order_Date              object
Mall                    object
City                    object
Product                 object
Category                object
Quantity               float64
Unit_Price_INR         float64
Discount               float64
Sales_Channel           object
Customer_Age           float64
Customer_Rating        float64

Cleaned data types:

                       Cleaned dtype
Order_ID                      object
Order_Date            datetime64[ns]
Mall                  string[python]
City                  string[python]
Product               string[python]
Category              string[python]
Quantity                     float64
Unit_Price_INR               float64
Discount                     float64
Sales_Channel         string[python]
Customer_Age                 float64
Customer_Rating              float64
Quantity_Capped_Demo         float64
Revenue                      float64

                 Before_Mean   After_Mean  Before_Median  After_Median
Quantity           14.157025    14.206612           4.00          4.00
Unit_Price_INR   1973.866364  1172.822645        1084.43       1085.94
Discount            0.108264     0.093388           0.10          0.10
Customer_Age       42.916667    42.173554          41.00         41.00
Customer_Rating     3.709167     3.721074           3.70          3.75

Total revenue in cleaned dataset: 876330.78

In [ ]:
Division 10 — Final validation and export
What: Validate business rules, inspect the final dataset, and save a cleaned CSV.
Why: A cleaning workflow should produce a reusable output and confirm that key rules hold.
Outcome: A cleaned CSV plus documented cleaning decisions.

In [11]:
assert (df["Quantity"] > 0).all()
assert (df["Unit_Price_INR"] > 0).all()
assert df["Discount"].between(0, 1).all()
assert df["Customer_Rating"].between(1, 5).all()

display(df.head())
display(df.tail())
print("Final shape:", df.shape)
print("Exact duplicates remaining:", df.duplicated().sum())
print("Remaining missing cells:", int(df.isna().sum().sum()))

df.to_csv("mall_ecommerce_cleaned_dataset.csv", index=False)
print("Saved: mall_ecommerce_cleaned_dataset.csv")

,Order_ID,Order_Date,Mall,City,Product,Category,Quantity,Unit_Price_INR,Discount,Sales_Channel,Customer_Age,Customer_Rating,Quantity_Capped_Demo,Revenue
0,ORD-0001,2025-05-10,Mall Central,Chennai,Coffee Mug,Home & Living,1.0,244.43,0.15,Click & Collect,62.0,4.2,1.0,207.77
1,ORD-0002,2025-08-09,Mall Central,Bengaluru,Water Bottle,Home & Living,2.0,455.93,0.00,In-Store,57.0,4.5,2.0,911.86
2,ORD-0003,2025-03-15,Mall Central,Mumbai,Keyboard,Electronics,4.0,1772.22,0.00,In-Store,37.0,4.8,4.0,7088.88
3,ORD-0004,2025-06-13,Riverside Mall,Chennai,Power Bank,Electronics,6.0,1424.78,0.15,In-Store,41.0,3.1,6.0,7266.38
4,ORD-0005,NaT,City Square,Bengaluru,Usb-C Cable,Electronics,1.0,259.87,0.10,Click & Collect,61.0,4.1,1.0,233.88

,Order_ID,Order_Date,Mall,City,Product,Category,Quantity,Unit_Price_INR,Discount,Sales_Channel,Customer_Age,Customer_Rating,Quantity_Capped_Demo,Revenue
116,ORD-0117,2025-07-19,City Square,Bengaluru,Keyboard,Electronics,3.0,1906.82,0.1,In-Store,51.0,4.9,3.0,5148.41
117,ORD-0118,2025-07-27,City Square,Pune,T-Shirt,Fashion,2.0,0.01,0.0,In-Store,39.0,3.7,2.0,0.02
118,ORD-0119,2025-10-12,Metro Plaza,Pune,Bluetooth Speaker,Electronics,1.0,2224.68,0.0,Click & Collect,32.0,3.3,1.0,2224.68
119,ORD-0120,2025-05-01,City Square,Hyderabad,Running Shoes,Fashion,5.0,3098.86,0.1,In-Store,51.0,3.5,5.0,13944.87
122,ORD-0031,2025-07-08,Grand Arcade,Pune,Water Bottle,Home & Living,5.0,416.94,0.1,Click & Collect,22.0,3.5,5.0,1876.23

Final shape: (121, 14)
Exact duplicates remaining: 0
Remaining missing cells: 10
Saved: mall_ecommerce_cleaned_dataset.csv